### ISSUE TITLE
Technical Direction of Website

### ISSUE THREAD

**Issue by oliverli** [hwachongirs/OurWebsite#1]
What technologies do we want to use for our website? NodeJS? PHP? Node.js? ASP.NET?!

After the general direction is set, we need some form of work assignment.

And everyone must remember to sync to GitHub - don't keep unsynced code on your computer for too long or prepare for the merge conflicts of your life.

**Comment by hwachongirs** [comment]
The Plan now is get JF to set up Nginx, PHP-fpm, mySQL, etc. While both of us get it configured, we use git to work on the website like just the simple landing pages (similar to http://comsci.club/) just use HTML for this I guess
